import mongoose from "mongoose";

const ArchitectureSchema = new mongoose.Schema({
  category: {
    type: String,
    enum: [
      "Residential",
      "Commercial",
      "Industrial",
      "Agricultural",
      "Recreational",
      "Institutional",
      "Mixed Use",
      "Infrastructural"
    ],
    required: true,
  },
  style: {
    type: String,
    enum: [
      "Classical",
      "Gothic",
      "Renaissance",
      "Baroque",
      "Neoclassical",
      "Victorian",
      "Beaux-Arts",
      "Art Nouveau",
      "Art Deco",
      "Modernism",
      "Bauhaus",
      "International",
      "Mid-Century Modern",
      "Brutalism",
      "Postmodernism",
      "Deconstructivism",
      "Minimalism",
      "Neo-Futurism",
      "Bohemian",
      "Eco-architecture",
      "-"
    ],
    required: true,
  },
  materialUsed: {
    type: [String],
    enum: [
      "Stone",
      "Brick",
      "Concrete",
      "Steel",
      "Glass",
      "Wood",
      "Bamboo",
      "Aluminum",
      "Copper",
      "Clay",
      "Plaster",
      "Adobe",
      "Rammed Earth",
      "Thatch",
      "Acrylic",
      "Fiber-reinforced",
      "-",
    ],
    default: [],
  },
  soilType: {
    type: String,
    enum: ["Loose", "Soft", "Firm", "Stiff", "Dense", "Hard", "Sandy", "Rock", "-"],
  },
  terrain: {
    type: String,
    enum: ["Flat", "Sloping", "Hilly", "Mountainous", "Coastal", "Waterfront", "Plateau", "Valley", "-"],
  },
  climateAdaptability: {
    type: String,
    enum: ["Hot & Dry", "Hot & Humid", "Cold", "Temperate", "Composite", "Tropical", "-", ""],
  },
  roofType: {
    type: String,
    enum: ["Flat", "Gable", "Hip", "Shed", "Mansard", "Gambrel", "Butterfly", "Dome", "Pyramid", "Curved", "Green", "Sawtooth", "-", ""],
  },
  interiorPlan: {
    type: String,
    enum: ["Open", "Closed", "Linear", "Centralized", "Radial", "Grid", "Cluster", "Split-Level", "Loft", "Courtyard", "Studio", "-", ""],
  },
  sustainability: {
    type: String,
    enum: [
      "Passive Solar Design",
      "Green Roofs",
      "Rainwater Harvesting",
      "Greywater Recycling",
      "Natural Ventilation",
      "Thermal Mass",
      "Daylighting",
      "Net-Zero Energy Design",
      "Low-Carbon Materials",
      "Recycled Materials",
      "Modular Construction",
      "Smart Glass",
      "Solar Panels",
      "Wind Energy Integration",
      "Geothermal Heating & Cooling",
      "Biomimicry Design",
      "BREEAM Standards",
      "Circular Economy Design",
      "Adaptive Reuse",
      "Carbon-Neutral Construction",
      "-",
    ],
  },
  additionalFeatures: {
    type: [String],
    enum: [
      "Balconies",
      "Verandas",
      "Terraces",
      "Patios",
      "Decks",
      "Pergolas",
      "Atriums",
      "Courtyards",
      "Bay Windows",
      "Skylights",
      "Chimneys",
      "Columns",
      "Arches",
      "Domes",
      "Spires",
      "Staircases",
      "Elevators",
      "Ramps",
      "Water Features",
      "Fireplaces",
      "Gates",
      "-",
    ],
    default: [],
  },
  exterior: {
    type: [String],
    enum: [
      "Façade",
      "Cladding",
      "Siding",
      "Stucco",
      "Brickwork",
      "Stone Veneer",
      "Glass Curtain Wall",
      "Timber Exterior",
      "Metal Panels",
      "Green Walls",
      "Pergolas",
      "Awnings",
      "Canopies",
      "Balconies",
      "Verandas",
      "Patios",
      "Decks",
      "Driveways",
      "Fences",
      "-",
    ],
    default: [],
  },
  buildingTypes: {
    residential: { type: [String], default: [] },
    commercial: { type: [String], default: [] },
    industrial: { type: [String], default: [] },
    agricultural: { type: [String], default: [] },
    recreational: { type: [String], default: [] },
    institutional: { type: [String], default: [] },
    mixedUse: { type: [String], default: [] },
    infrastructural: { type: [String], default: [] }
  },
}, { timestamps: true });

export default mongoose.model("Architecture", ArchitectureSchema);
